### ISSUE TITLE
关于设置时区导致程序报错

### ISSUE THREAD

**Issue by TNXG** [ArtalkJS/Artalk#448]
#418 

在佬们更新了这个功能后我也对于我老旧的Replit上部署的Artalk进行了更新（原来的版本是2.3.0）

在更新完成后出现了时区问题

在配置项中配置`timezone: "Asia/Shanghai"`后报错
```
panic: time: missing Location in call to Time.In

goroutine 1 [running]:
time.Time.In(...)
    /usr/local/go/src/time/time.go:1146
github.com/gofiber/fiber/v2/middleware/logger.New({0xc001159af8, 0x1, 0x1})
    /go/pkg/mod/github.com/gofiber/fiber/v2@v2.42.0/middleware/logger/logger.go:39 +0x919
github.com/ArtalkJS/Artalk/cmd.glob..func6(0x25da040?, {0x2f8fa68?, 0x0?, 0x0?})
    /workspaces/Artalk/cmd/server.go:36 +0x1b0
github.com/spf13/cobra.(*Command).execute(0x25da040, {0x2f8fa68, 0x0, 0x0})
    /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x25d9d60)
    /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/ArtalkJS/Artalk/cmd.Execute()
    /workspaces/Artalk/cmd/root.go:47 +0x25
main.main()
    /workspaces/Artalk/main.go:17 +0x3c
exit status 2
```
而使用`timezone: "UTC"`则可以正常启动

想问问如果使用UTC时区会有什么奇怪的事情发生么（bushi

（使用codespaces构建

**Comment by qwqcode** [comment]
这可能和你的系统环境有关，Golang 的时区功能依赖 `tzdata` 数据库

例如你可以在 Debian Linux 执行以下命令安装这个依赖：

```sh
apk add tzdata
```

参考：https://segmentfault.com/a/1190000014967489

**Comment by TNXG** [comment]
在`replit.nix`中添加关于`pkgs.tzdata`的配置项还是如上报错
![image](https://user-images.githubusercontent.com/69001561/223430093-9d8c241c-ef20-4a3f-af21-a012f5bb7b54.png)
