### ISSUE TITLE
页面需要刷新才可以显示评论框

### ISSUE THREAD

**Issue by EternalCK** [ArtalkJS/Artalk#470]
进入页面不显示artalk，需要手动刷新页面才可以看到artalk

**Comment by qwqcode** [comment]
可以提供下具体有问题的页面链接，Artalk版本号等信息吗

**Comment by EternalCK** [comment]
![image](https://user-images.githubusercontent.com/113754238/227764993-9fc1d222-ab40-4e8a-a4bd-31e12b7b2273.png)

**Comment by EternalCK** [comment]
> 可以提供下具体有问题的页面链接，Artalk版本号等信息吗

![image](https://user-images.githubusercontent.com/113754238/227765047-cf3723f5-5432-4c3b-b8e2-bfff0bbf8160.png)

博客地址 :https://blogs.cwkl.love

**Comment by EternalCK** [comment]
运行2.5.2 项目一直崩溃

![image](https://user-images.githubusercontent.com/113754238/227778222-c93d5229-e749-4711-859a-c061b7f0830d.png)

**Comment by EternalCK** [comment]
2.5.2可以显示，但是出现新的错误
![image](https://user-images.githubusercontent.com/113754238/227790446-1ee1269c-d69a-49b9-b203-18ff5a74a119.png)

**Comment by EternalCK** [comment]
能不能适配一下Docusaurus2
下面代码现在用的 2.5.1 刷新才显示评论
其他版本就直接设置有问题，导致崩溃。
```
import React, { useEffect }  from 'react'
import 'artalk/dist/Artalk.css'
import BrowserOnly from '@docusaurus/BrowserOnly';
export default function Comment(): JSX.Element {
  return (
    <BrowserOnly fallback={<div>Loading Comments...</div>}>
      {() => {
        const Artalk = require('artalk').default;
        useEffect(() => {
          Artalk.init({
            el: '#comment',
            pageKey: `${window.location.pathname}`,
            pageTitle: `${window.document.title}`,
            server: 'https://artalk.ysicing.cloud/',
            site: '缘生笔记',
          });
        });
        return <div id="comment" className="artalk-comments" />;
      }}
    </BrowserOnly>
  );
}
```

**Comment by qwqcode** [comment]
请使用 Artalk 最新版本，并参考 Artalk API 文档在您项目的生命周期合适位置执行 `Artalk.init()` 初始化 Artalk，并在页面切换时执行 `Artalk.update()` 和 `Artalk.reload()` 更新页面配置和重载评论列表。

---

在 React 项目中引入 Artalk 可通过如下步骤：

1. 创建一个名为 Artalk 的组件
2. 在需要显示评论的页面中引入评论组件

```tsx
import React, { Component } from 'react';
import Artalk from 'artalk';

class ArtalkWrapper extends Component {
  componentDidMount() {
    Artalk.init({
      el: '#comments',
      pageKey: window.location.pathname,
      pageTitle: window.document.title,
      server: 'https://artalk.your_domain.com',
      site: '站点名',
    });
  }

  componentDidUpdate(prevProps) {
    if (this.props.location !== prevProps.location) {
      // 页面发生切换后更新Artalk配置
      Artalk.update({
        pageKey: window.location.pathname,
        pageTitle: window.document.title,
      });

      // 重新加载评论列表
      Artalk.reload();
    }
  }

  render() {
    return (
      <div id="comments"></div>
    );
  }
}

export default ArtalkWrapper;
```

在上面的示例中，`componentDidUpdate()` 方法是 React 组件中的一个生命周期方法，它会在组件更新完成后被调用。我们可以在这个方法中监听 this.props.location 的变化，如果变化了，就执行 `Artalk.update({})` 代码修改 Artalk 配置，并执行 `Artalk.reload()` 重新加载评论列表。

组件引入示例：

```tsx
import React from 'react';
import Layout from '@theme/Layout';
import Artalk from '../components/Artalk';

function MyPage() {
  return (
    <Layout>
      <div className="container">
        <h1>My Page</h1>
        <p>Welcome to my page!</p>
        <Artalk />
      </div>
    </Layout>
  );
}

export default MyPage;
```

在上面的示例中，我们在 MyPage 组件中引入了 Artalk 组件，并将其放置在 `<div>` 元素中。这样，当 MyPage 组件被渲染时，Artalk 组件也会被渲染，从而在页面上显示评论系统。

更多参考：

- https://artalk.js.org/develop/fe-api.html
- https://dev.to/m19v/how-to-add-giscus-comments-to-docusaurus-439h
- https://github.com/ArtalkJS/Artalk/blob/master/docs/.vitepress/theme/Artalk.vue

**Comment by EternalCK** [comment]
> build不成功

```
[ERROR] Docusaurus server-side rendering could not render static page with path /about.
[INFO] It looks like you are using code that should run on the client-side only.
To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
[ERROR] Docusaurus server-side rendering could not render static page with path /friends/.
[ERROR] Docusaurus server-side rendering could not render static page with path /posts/blog-notice.
[ERROR] Docusaurus server-side rendering could not render static page with path /posts/docker.
[ERROR] Docusaurus server-side rendering could not render static page with path /posts/Getting Umami.
[ERROR] Docusaurus server-side rendering could not render static page with path /read/2023okr.
[ERROR] Docusaurus server-side rendering could not render static page with path /read/hard life.
[ERROR] Docusaurus server-side rendering could not render static page with path /read/jinrishici.
[ERROR] Docusaurus server-side rendering could not render static page with path /read/spring.
[ERROR] Docusaurus server-side rendering could not render static page with path /site.
[ERROR] Docusaurus server-side rendering could not render static page with path /sponsor.
[ERROR] Docusaurus server-side rendering could not render static page with path /todo.
[ERROR] Docusaurus server-side rendering could not render static page with path /tools/appleID.
[ERROR] Docusaurus server-side rendering could not render static page with path /tools/artalk.
[ERROR] Docusaurus server-side rendering could not render static page with path /tools/free-clash.
[ERROR] Docusaurus server-side rendering could not render static page with path /tools/soft-ol.
[ERROR] Docusaurus server-side rendering could not render static page with path /tools/win11install.


ReferenceError: window is not defined
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
TypeError: Cannot read properties of undefined (reading 'BX')
TypeError: Cannot read properties of undefined (reading 'BX')
TypeError: Cannot read properties of undefined (reading 'BX')
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
ReferenceError: Cannot access 'components_Comment' before initialization
[ERROR] Unable to build website for locale zh-Hans.
[ERROR] Error: Failed to compile with errors.
    at C:\Users\t1301\Downloads\site projects\2023 - 原件-禁止加载 - 副本\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at C:\Users\t1301\Downloads\site projects\2023 - 原件-禁止加载 - 副本\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\t1301\Downloads\site projects\2023 - 原件-禁止加载 - 副本\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO] Docusaurus version: 2.3.1
Node version: v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

进程已结束,退出代码1
```

**Comment by ysicing** [comment]
更新到2.5.2就可以了， 示例 https://ysicing.me/tools/artalk

**Comment by EternalCK** [comment]
> 更新到2.5.2就可以了， 示例 https://ysicing.me/tools/artalk

你试试点击文章右侧目录，有新的错误
![image](https://user-images.githubusercontent.com/113754238/229033795-514b6072-6004-44f2-9562-92ec9787a3c3.png)
