### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by Mister-Hope** [ArtalkJS/Artalk#675]
It would be great for artalk to support SSR (or SSG in another way).

To support this, artalk must not access any dom realted variables before actual api call (i.e.: `Artalk.init`)

Currently artalk is at least accessing window object in main context.

## Solution

before:

```ts
// ...
window.localstorage
// ...

export default class Aralk {
  // ..
}
```

after:

```ts
// ...

const getLocalConfig = () => {
 // ...
  window.localstorage
 // ...

 return xxx;
}

// ...

export default class Aralk {
  // ..
  init() {
   const config = getLocalConfig()
  }
  // ...
}
```

```sh
ReferenceError: window is not defined
    at new <anonymous> (/home/mister-hope/projects/vuepress/vuepress-theme-hope/node_modules/.pnpm/artalk@2.7.1/node_modules/artalk/dist/Artalk.js:1:10052)
    at /home/mister-hope/projects/vuepress/vuepress-theme-hope/node_modules/.pnpm/artalk@2.7.1/node_modules/artalk/dist/Artalk.js:1:9941
    at /home/mister-hope/projects/vuepress/vuepress-theme-hope/node_modules/.pnpm/artalk@2.7.1/node_modules/artalk/dist/Artalk.js:1:1281
    at Object.<anonymous> (/home/mister-hope/projects/vuepress/vuepress-theme-hope/node_modules/.pnpm/artalk@2.7.1/node_modules/artalk/dist/Artalk.js:1:1419)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by qwqcode** [comment]
感谢反馈，这个问题是我以前没有考虑到的，现在正在进行持续改进！

**Comment by Mister-Hope** [comment]
我晚点提一个pr修复它

**Comment by qwqcode** [comment]
我再测测，非常感谢！

**Comment by qwqcode** [comment]
<img width="840" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/523839ac-c9fe-4afa-86c9-a58de9848d51">

目前这个测试用例已经通过编译，之前会报 window undefined 的错误：

https://github.com/ArtalkJS/Artalk/blob/master/test/ssg-test/.vitepress/theme/Artalk.vue

该用例中包含：

- 在 SSG 编译时 `import Artalk from 'artalk'` 引入而不是 `import('artalk')` 动态引入
- 在 `onMounted` 外调用 `Artalk.use` (非 `Artalk.init` 的方法，没有引用 window) 不报错
- 在 `onMounted` 和 `onUnmounted` 以及 `watch` 调用 `Artalk.init`, `Artalk.update` 和 `Artalk.destroy` 不报错

相关参考文档：

- https://vitepress.dev/guide/ssr-compat#ssr-compatibility
- https://vuejs.org/guide/scaling-up/ssr.html

fixes #608
