### ISSUE TITLE
React 例子导致无限递归

### ISSUE THREAD

**Issue by frostming** [ArtalkJS/Artalk#716]
你好，我用文档上提供的[React例子](https://artalk.js.org/guide/frontend/import-framework.html#react)

```js
import React, { useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import 'artalk/dist/Artalk.css';
import Artalk from 'artalk';

const ArtalkComment = () => {
  const el = useRef(null);
  const location = useLocation();
  let artalk = null;

  useEffect(() => {
    artalk = new Artalk({
      el: el.current,
      pageKey: location.pathname,
      pageTitle: document.title,
      server: 'http://localhost:8080',
      site: 'Artalk 的博客',
      // ...
    });

    return () => {
      if (artalk) {
        artalk.destroy();
      }
    };
  }, [location.pathname]);

  return <div ref={el}></div>;
};

export default ArtalkComment;
```

渲染后出现错误：

```
react-dom.development.js:22839 Uncaught RangeError: Maximum call stack size exceeded
    at eval (Artalk.es.js:231:1)
    at Array.forEach (<anonymous>)
    at mergeDeep (Artalk.es.js:231:1)
    at eval (Artalk.es.js:237:1)
    at Array.forEach (<anonymous>)
    at mergeDeep (Artalk.es.js:231:1)
    at eval (Artalk.es.js:237:1)
    at Array.forEach (<anonymous>)
    at mergeDeep (Artalk.es.js:231:1)
    at eval (Artalk.es.js:237:1)
    at Array.forEach (<anonymous>)
    at mergeDeep (Artalk.es.js:231:1)
    at eval (Artalk.es.js:237:1)
    at Array.forEach (<anonymous>)
    ...
```

研究发现[这一行](https://github.com/ArtalkJS/Artalk/blob/60e0e7e61a412b678d9666f059a26d86e19788f9/ui/artalk/src/config.ts#L14) 会inplace更新 `Defaults`，若 config 中 `el` 的值为一个react ref，这时这个元素会包含递归引用（它的`ref` 属性指向自己的ref），而 `mergeDeep` 是一个递归操作，造成无限递归。

解决方法是修改 `mergeDeep`，使它不要更新 `Defaults`

**Comment by qwqcode** [comment]
谢谢你的耐心检查与反馈！❤️
