### ISSUE TITLE
升级到 v2.8.7 后 Artalk 无法启动

### ISSUE THREAD

**Issue by Big-Cake-jpg** [ArtalkJS/Artalk#943]
此前一直在用 Artalk v2.8.6，最近尝试更新到 v2.8.7，结果反复出现下述错误：

```log
2024/07/11 11:11:21.655 ERROR [dao/query_find_create.go:50] [DB] {"error": "Error 1062 (23000): Duplicate entry '晓雨杂记' for key 'sites.idx_sites_name'", "elapsed": 0.002292665, "rows": 0, "sql": "INSERT INTO `sites` (`created_at`,`updated_at`,`deleted_at`,`name`,`urls`) VALUES ('2024-07-11 11:11:21.653','2024-07-11 11:11:21.653',NULL,'晓雨杂记','')"}
2024/07/11 11:11:21.655 ERROR [dao/query_new.go:16] Create Site error: Error 1062 (23000): Duplicate entry '晓雨杂记' for key 'sites.idx_sites_name'
Jul 11 11:06:33 C20240413202925 artalk[254558]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 11 11:06:33 C20240413202925 artalk[254558]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfaac15]
Jul 11 11:06:33 C20240413202925 artalk[254558]: goroutine 24 [running]:
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/nikoksr/notify/service/telegram.(*Telegram).AddReceivers(...)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /root/go/pkg/mod/github.com/nikoksr/notify@v0.41.0/service/telegram/telegram.go:60
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/internal/notify_pusher.(*NotifyPusher).loadHelper(0xc0001a2510)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/internal/notify_pusher/base.go:54 +0x95
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/internal/notify_pusher.NewNotifyPusher(0xc0002de160)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/internal/notify_pusher/base.go:39 +0xa6
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/internal/core.(*NotifyService).Init(0xc0004796f0)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/internal/core/service_notify.go:20 +0x11e
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/internal/core.(*App).Bootstrap(0xc0002e54d0)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/internal/core/base.go:118 +0x3fc
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).addCommand.func1(0xc0003f5508, {0xc000093140, 0x0, 0x4})
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/cmd/base.go:106 +0x3b1Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/spf13/cobra.(*Command).execute(0xc0003f5508, {0xc0000930c0, 0x4, 0x4})
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:972 +0xa1f
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f5208)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/spf13/cobra.(*Command).Execute(...)
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
Jul 11 11:06:33 C20240413202925 artalk[254558]: github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2()
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/cmd/base.go:151 +0x25
Jul 11 11:06:33 C20240413202925 artalk[254558]: created by github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch in goroutine 1
Jul 11 11:06:33 C20240413202925 artalk[254558]:         /go/src/github.com/ArtalkJS/Artalk/cmd/base.go:150 +0xbc
```

数据库是 MySQL，无论使用 Docker 部署还是二进制部署均是如此。

**Comment by Big-Cake-jpg** [comment]
感觉像是和 Telegram 推送有关系，我开了 Debug，试了下禁用掉 Telegram 通知以后恢复正常了，再打开就又无法启动了。

2.8.6 似乎也时不时存在这个问题。

**Comment by qwqcode** [comment]
检查下是不是网络问题

**Comment by qwqcode** [comment]
我刚刚修改了代码，增加了 tg 的错误提示，尝试更新到 Nightly 版本看看有没有详细的错误信息

**Comment by Big-Cake-jpg** [comment]
> 我刚刚修改了代码，增加了 tg 的错误提示，尝试更新到 Nightly 版本看看有没有详细的错误信息

看起来似乎是 DNS 污染，我这边试着切一下 DNS 好了。

```
2024/07/11 14:28:46.218 ERROR [dao/query_new.go:16] Create Site error: Error 1062 (23000): Duplicate entry '晓雨杂记' for key 'sites.idx_sites_name'
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).NewSite
	/source/internal/dao/query_new.go:16
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite.func2
	/source/internal/dao/query_find_create.go:50
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...].func1
	/source/internal/dao/query_find_create.go:33
golang.org/x/sync/singleflight.(*Group).doCall.func2
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:198
golang.org/x/sync/singleflight.(*Group).doCall
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:200
golang.org/x/sync/singleflight.(*Group).Do
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:113
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...]
	/source/internal/dao/query_find_create.go:27
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite
	/source/internal/dao/query_find_create.go:47
github.com/ArtalkJS/Artalk/internal/core.(*App).syncFromConf
	/source/internal/core/conf_sync.go:9
github.com/ArtalkJS/Artalk/internal/core.(*App).Bootstrap
	/source/internal/core/base.go:114
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).addCommand.func1
	/source/cmd/base.go:106
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:972
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2
	/source/cmd/base.go:151
2024/07/11 14:28:46.219 DEBUG [email/queue.go:34] [Email] Email Queue initialize complete
2024/07/11 14:28:46.934 ERROR [notify_pusher/base.go:58] [Notify] Telegram service init error: Post "https://api.telegram.org/bot6691863892:AAEb0RjjHXxL8l6OodOsqgCcyBN9Bk0OMUY/getMe": tls: failed to verify certificate: x509: certificate is valid for *.facebook.com, *.facebook.net, *.fbcdn.net, *.fbsbx.com, *.m.facebook.com, *.messenger.com, *.xx.fbcdn.net, *.xy.fbcdn.net, *.xz.fbcdn.net, facebook.com, messenger.com, not api.telegram.org
github.com/ArtalkJS/Artalk/internal/notify_pusher.(*NotifyPusher).loadHelper
	/source/internal/notify_pusher/base.go:58
github.com/ArtalkJS/Artalk/internal/notify_pusher.NewNotifyPusher
	/source/internal/notify_pusher/base.go:40
github.com/ArtalkJS/Artalk/internal/core.(*NotifyService).Init
	/source/internal/core/service_notify.go:20
github.com/ArtalkJS/Artalk/internal/core.(*App).Bootstrap
	/source/internal/core/base.go:118
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).addCommand.func1
	/source/cmd/base.go:106
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:972
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2
	/source/cmd/base.go:151
```

不过还有一个数据库相关的问题：

```
2024/07/11 14:36:42.816 ERROR [dao/query_find_create.go:50] [DB] {"error": "Error 1062 (23000): Duplicate entry '晓雨杂记' for key 'sites.idx_sites_name'", "elapsed": 0.005668767, "rows": 0, "sql": "INSERT INTO `sites` (`created_at`,`updated_at`,`deleted_at`,`name`,`urls`) VALUES ('2024-07-11 14:36:42.811','2024-07-11 14:36:42.811',NULL,'晓雨杂记','')"}
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite.func2
	/source/internal/dao/query_find_create.go:50
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...].func1
	/source/internal/dao/query_find_create.go:33
golang.org/x/sync/singleflight.(*Group).doCall.func2
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:198
golang.org/x/sync/singleflight.(*Group).doCall
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:200
golang.org/x/sync/singleflight.(*Group).Do
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:113
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...]
	/source/internal/dao/query_find_create.go:27
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite
	/source/internal/dao/query_find_create.go:47
github.com/ArtalkJS/Artalk/internal/core.(*App).syncFromConf
	/source/internal/core/conf_sync.go:9
github.com/ArtalkJS/Artalk/internal/core.(*App).Bootstrap
	/source/internal/core/base.go:114
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).addCommand.func1
	/source/cmd/base.go:106
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:972
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2
	/source/cmd/base.go:151
2024/07/11 14:36:42.817 ERROR [dao/query_new.go:16] Create Site error: Error 1062 (23000): Duplicate entry '晓雨杂记' for key 'sites.idx_sites_name'
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).NewSite
	/source/internal/dao/query_new.go:16
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite.func2
	/source/internal/dao/query_find_create.go:50
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...].func1
	/source/internal/dao/query_find_create.go:33
golang.org/x/sync/singleflight.(*Group).doCall.func2
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:198
golang.org/x/sync/singleflight.(*Group).doCall
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:200
golang.org/x/sync/singleflight.(*Group).Do
	/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:113
github.com/ArtalkJS/Artalk/internal/dao.FindCreateAction[...]
	/source/internal/dao/query_find_create.go:27
github.com/ArtalkJS/Artalk/internal/dao.(*Dao).FindCreateSite
	/source/internal/dao/query_find_create.go:47
github.com/ArtalkJS/Artalk/internal/core.(*App).syncFromConf
	/source/internal/core/conf_sync.go:9
github.com/ArtalkJS/Artalk/internal/core.(*App).Bootstrap
	/source/internal/core/base.go:114
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).addCommand.func1
	/source/cmd/base.go:106
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:972
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2
	/source/cmd/base.go:151
```

**Comment by Big-Cake-jpg** [comment]
已确定数据库问题是缓存所致，关闭缓存后正常部署。
